### ISSUE TITLE
Unable to pick block with another mod installed

### ISSUE THREAD

**Issue by encumber** [Sjouwer/pick-block-pro#16] opened 2023-06-28 00:57 UTC
With the visiblebarriers mod (very useful mod for mapmaking) pick block stops working as it allows you to pickblock air, if there was a blacklist for blocks instead of tags that would make it very helpful as there is currently no way that I know of to blacklist the air block from this mod which is every air block

**Comment by Sjouwer** [comment] 2023-06-29 21:54
Sounds like something more is going on, it shouldn't just be picking air, doubt that's also what happens with the default pick block. I'll look into it very soon, thank you for the report

**Comment by Sjouwer** [comment] 2023-06-30 16:52
I've tried to reproduce the issue, but I've been unable to do so. Which mc version do you play on and which versions of the mods do you use? Do you have any other mods installed that could potentially be causing this?

**Comment by Sjouwer** [comment] 2023-06-30 17:02
Found this issue which seems to be related:
https://github.com/AmyMialeeMods/visible-barriers/issues/22
Looks like the issue is between Litematica and Visible barriers.
So it seems there is nothing that can be done about this on my end

Edit:
I can confirm, I added litematica and could only pick air. This is an issue with the block picker from Litematica and not Pick Block Pro. I'll be closing this issue now.

**Closed as completed** 2023-06-30 17:16 UTC
